### ISSUE TITLE
Using commands in terminal

### ISSUE THREAD

**Issue by nikonet** [srascar/galaxy-migrations#6]
Hi, after some experimentation I finally found out how to use this, by writing "**node ./node_modules/@srascar/galaxy-migrations/galaxy-migrations generate**". 

I'm wondering if there is a better way to do this, as it's a bit painful to write all that every time. Maybe some import-export way, or setting up a script in package.json?

**Comment by srascar** [comment]
Hi, I will see if I can add the command to the bin directory to make things easier

**Comment by srascar** [comment]
hi, I've updated the path  here.
https://github.com/srascar/galaxy-migrations/blob/master/package.json#L6

can you please tell me if it's still an issue ?

**Comment by srascar** [comment]
Documentation has been updated too.
https://github.com/srascar/galaxy-migrations/blob/v1.0.5/README.md#usage

Issue can be closed
